spring.application.name=chess-lan-backend
server.address=0.0.0.0
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/chess_game
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

jwt.secret=Y2hlc3MtbGFuLWJhY2tlbmQtZGV2ZWxvcG1lbnQtc2VjcmV0LWtleS0yMDI2
jwt.access-token-exp-minutes=30

springdoc.swagger-ui.path=/swagger-ui.html
